// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: center.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CenterRequest 请求消息
type CenterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CenterRequest_PlayerOnline
	//	*CenterRequest_PlayerOffline
	//	*CenterRequest_PlayerQuery
	//	*CenterRequest_Heartbeat
	Request       isCenterRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CenterRequest) Reset() {
	*x = CenterRequest{}
	mi := &file_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CenterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterRequest) ProtoMessage() {}

func (x *CenterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterRequest.ProtoReflect.Descriptor instead.
func (*CenterRequest) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{0}
}

func (x *CenterRequest) GetRequest() isCenterRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CenterRequest) GetPlayerOnline() *PlayerOnline {
	if x != nil {
		if x, ok := x.Request.(*CenterRequest_PlayerOnline); ok {
			return x.PlayerOnline
		}
	}
	return nil
}

func (x *CenterRequest) GetPlayerOffline() *PlayerOffline {
	if x != nil {
		if x, ok := x.Request.(*CenterRequest_PlayerOffline); ok {
			return x.PlayerOffline
		}
	}
	return nil
}

func (x *CenterRequest) GetPlayerQuery() *PlayerQuery {
	if x != nil {
		if x, ok := x.Request.(*CenterRequest_PlayerQuery); ok {
			return x.PlayerQuery
		}
	}
	return nil
}

func (x *CenterRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Request.(*CenterRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isCenterRequest_Request interface {
	isCenterRequest_Request()
}

type CenterRequest_PlayerOnline struct {
	PlayerOnline *PlayerOnline `protobuf:"bytes,1,opt,name=player_online,json=playerOnline,proto3,oneof"` // 玩家上线
}

type CenterRequest_PlayerOffline struct {
	PlayerOffline *PlayerOffline `protobuf:"bytes,2,opt,name=player_offline,json=playerOffline,proto3,oneof"` // 玩家下线
}

type CenterRequest_PlayerQuery struct {
	PlayerQuery *PlayerQuery `protobuf:"bytes,3,opt,name=player_query,json=playerQuery,proto3,oneof"` // 查询玩家位置
}

type CenterRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"` // 心跳
}

func (*CenterRequest_PlayerOnline) isCenterRequest_Request() {}

func (*CenterRequest_PlayerOffline) isCenterRequest_Request() {}

func (*CenterRequest_PlayerQuery) isCenterRequest_Request() {}

func (*CenterRequest_Heartbeat) isCenterRequest_Request() {}

// CenterResponse 响应消息
type CenterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CenterResponse_OnlineResult
	//	*CenterResponse_OfflineResult
	//	*CenterResponse_QueryResult
	//	*CenterResponse_HeartbeatResult
	//	*CenterResponse_KickPlayer
	//	*CenterResponse_Broadcast
	Response      isCenterResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CenterResponse) Reset() {
	*x = CenterResponse{}
	mi := &file_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CenterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterResponse) ProtoMessage() {}

func (x *CenterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterResponse.ProtoReflect.Descriptor instead.
func (*CenterResponse) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{1}
}

func (x *CenterResponse) GetResponse() isCenterResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CenterResponse) GetOnlineResult() *PlayerOnlineResult {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_OnlineResult); ok {
			return x.OnlineResult
		}
	}
	return nil
}

func (x *CenterResponse) GetOfflineResult() *PlayerOfflineResult {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_OfflineResult); ok {
			return x.OfflineResult
		}
	}
	return nil
}

func (x *CenterResponse) GetQueryResult() *PlayerQueryResult {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *CenterResponse) GetHeartbeatResult() *HeartbeatResult {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_HeartbeatResult); ok {
			return x.HeartbeatResult
		}
	}
	return nil
}

func (x *CenterResponse) GetKickPlayer() *KickPlayer {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_KickPlayer); ok {
			return x.KickPlayer
		}
	}
	return nil
}

func (x *CenterResponse) GetBroadcast() *BroadcastMessage {
	if x != nil {
		if x, ok := x.Response.(*CenterResponse_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isCenterResponse_Response interface {
	isCenterResponse_Response()
}

type CenterResponse_OnlineResult struct {
	OnlineResult *PlayerOnlineResult `protobuf:"bytes,1,opt,name=online_result,json=onlineResult,proto3,oneof"` // 上线结果
}

type CenterResponse_OfflineResult struct {
	OfflineResult *PlayerOfflineResult `protobuf:"bytes,2,opt,name=offline_result,json=offlineResult,proto3,oneof"` // 下线结果
}

type CenterResponse_QueryResult struct {
	QueryResult *PlayerQueryResult `protobuf:"bytes,3,opt,name=query_result,json=queryResult,proto3,oneof"` // 查询结果
}

type CenterResponse_HeartbeatResult struct {
	HeartbeatResult *HeartbeatResult `protobuf:"bytes,4,opt,name=heartbeat_result,json=heartbeatResult,proto3,oneof"` // 心跳结果
}

type CenterResponse_KickPlayer struct {
	KickPlayer *KickPlayer `protobuf:"bytes,5,opt,name=kick_player,json=kickPlayer,proto3,oneof"` // 踢人指令
}

type CenterResponse_Broadcast struct {
	Broadcast *BroadcastMessage `protobuf:"bytes,6,opt,name=broadcast,proto3,oneof"` // 广播消息
}

func (*CenterResponse_OnlineResult) isCenterResponse_Response() {}

func (*CenterResponse_OfflineResult) isCenterResponse_Response() {}

func (*CenterResponse_QueryResult) isCenterResponse_Response() {}

func (*CenterResponse_HeartbeatResult) isCenterResponse_Response() {}

func (*CenterResponse_KickPlayer) isCenterResponse_Response() {}

func (*CenterResponse_Broadcast) isCenterResponse_Response() {}

// PlayerOnline 玩家上线
type PlayerOnline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`     // 玩家 ID
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`           // game 服务器 ID
	LoginTime     int64                  `protobuf:"varint,3,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"` // 登录时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOnline) Reset() {
	*x = PlayerOnline{}
	mi := &file_center_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnline) ProtoMessage() {}

func (x *PlayerOnline) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnline.ProtoReflect.Descriptor instead.
func (*PlayerOnline) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerOnline) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOnline) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerOnline) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

// PlayerOffline 玩家下线
type PlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`        // 玩家 ID
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`              // game 服务器 ID
	LogoutTime    int64                  `protobuf:"varint,3,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"` // 登出时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOffline) Reset() {
	*x = PlayerOffline{}
	mi := &file_center_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOffline) ProtoMessage() {}

func (x *PlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOffline.ProtoReflect.Descriptor instead.
func (*PlayerOffline) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerOffline) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOffline) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerOffline) GetLogoutTime() int64 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

// PlayerQuery 查询玩家位置
type PlayerQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerQuery) Reset() {
	*x = PlayerQuery{}
	mi := &file_center_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQuery) ProtoMessage() {}

func (x *PlayerQuery) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQuery.ProtoReflect.Descriptor instead.
func (*PlayerQuery) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerQuery) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// Heartbeat 心跳
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // game 服务器 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_center_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// PlayerOnlineResult 上线结果
type PlayerOnlineResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOnlineResult) Reset() {
	*x = PlayerOnlineResult{}
	mi := &file_center_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOnlineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnlineResult) ProtoMessage() {}

func (x *PlayerOnlineResult) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnlineResult.ProtoReflect.Descriptor instead.
func (*PlayerOnlineResult) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerOnlineResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerOnlineResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayerOfflineResult 下线结果
type PlayerOfflineResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOfflineResult) Reset() {
	*x = PlayerOfflineResult{}
	mi := &file_center_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOfflineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOfflineResult) ProtoMessage() {}

func (x *PlayerOfflineResult) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOfflineResult.ProtoReflect.Descriptor instead.
func (*PlayerOfflineResult) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerOfflineResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerOfflineResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayerQueryResult 查询结果
type PlayerQueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`              // 是否在线
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 所在 game 服务器 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerQueryResult) Reset() {
	*x = PlayerQueryResult{}
	mi := &file_center_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQueryResult) ProtoMessage() {}

func (x *PlayerQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQueryResult.ProtoReflect.Descriptor instead.
func (*PlayerQueryResult) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerQueryResult) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PlayerQueryResult) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// HeartbeatResult 心跳结果
type HeartbeatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResult) Reset() {
	*x = HeartbeatResult{}
	mi := &file_center_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResult) ProtoMessage() {}

func (x *HeartbeatResult) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResult.ProtoReflect.Descriptor instead.
func (*HeartbeatResult) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResult) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// KickPlayer 踢人指令（center -> game）
type KickPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                     // 原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayer) Reset() {
	*x = KickPlayer{}
	mi := &file_center_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayer) ProtoMessage() {}

func (x *KickPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayer.ProtoReflect.Descriptor instead.
func (*KickPlayer) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{10}
}

func (x *KickPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *KickPlayer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BroadcastMessage 广播消息（center -> game）
type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []string               `protobuf:"bytes,1,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // 目标玩家（空表示全服）
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                      // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_center_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_center_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_center_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastMessage) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *BroadcastMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_center_proto protoreflect.FileDescriptor

const file_center_proto_rawDesc = "" +
	"\n" +
	"\fcenter.proto\x12\tframework\"\x90\x02\n" +
	"\rCenterRequest\x12>\n" +
	"\rplayer_online\x18\x01 \x01(\v2\x17.framework.PlayerOnlineH\x00R\fplayerOnline\x12A\n" +
	"\x0eplayer_offline\x18\x02 \x01(\v2\x18.framework.PlayerOfflineH\x00R\rplayerOffline\x12;\n" +
	"\fplayer_query\x18\x03 \x01(\v2\x16.framework.PlayerQueryH\x00R\vplayerQuery\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.framework.HeartbeatH\x00R\theartbeatB\t\n" +
	"\arequest\"\xae\x03\n" +
	"\x0eCenterResponse\x12D\n" +
	"\ronline_result\x18\x01 \x01(\v2\x1d.framework.PlayerOnlineResultH\x00R\fonlineResult\x12G\n" +
	"\x0eoffline_result\x18\x02 \x01(\v2\x1e.framework.PlayerOfflineResultH\x00R\rofflineResult\x12A\n" +
	"\fquery_result\x18\x03 \x01(\v2\x1c.framework.PlayerQueryResultH\x00R\vqueryResult\x12G\n" +
	"\x10heartbeat_result\x18\x04 \x01(\v2\x1a.framework.HeartbeatResultH\x00R\x0fheartbeatResult\x128\n" +
	"\vkick_player\x18\x05 \x01(\v2\x15.framework.KickPlayerH\x00R\n" +
	"kickPlayer\x12;\n" +
	"\tbroadcast\x18\x06 \x01(\v2\x1b.framework.BroadcastMessageH\x00R\tbroadcastB\n" +
	"\n" +
	"\bresponse\"c\n" +
	"\fPlayerOnline\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"login_time\x18\x03 \x01(\x03R\tloginTime\"f\n" +
	"\rPlayerOffline\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vlogout_time\x18\x03 \x01(\x03R\n" +
	"logoutTime\"*\n" +
	"\vPlayerQuery\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"H\n" +
	"\x12PlayerOnlineResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x13PlayerOfflineResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x11PlayerQueryResult\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"2\n" +
	"\x0fHeartbeatResult\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"A\n" +
	"\n" +
	"KickPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x10BroadcastMessage\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\tR\tplayerIds\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2R\n" +
	"\rCenterService\x12A\n" +
	"\x06Stream\x12\x18.framework.CenterRequest\x1a\x19.framework.CenterResponse(\x010\x01B;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_center_proto_rawDescOnce sync.Once
	file_center_proto_rawDescData []byte
)

func file_center_proto_rawDescGZIP() []byte {
	file_center_proto_rawDescOnce.Do(func() {
		file_center_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_center_proto_rawDesc), len(file_center_proto_rawDesc)))
	})
	return file_center_proto_rawDescData
}

var file_center_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_center_proto_goTypes = []any{
	(*CenterRequest)(nil),       // 0: framework.CenterRequest
	(*CenterResponse)(nil),      // 1: framework.CenterResponse
	(*PlayerOnline)(nil),        // 2: framework.PlayerOnline
	(*PlayerOffline)(nil),       // 3: framework.PlayerOffline
	(*PlayerQuery)(nil),         // 4: framework.PlayerQuery
	(*Heartbeat)(nil),           // 5: framework.Heartbeat
	(*PlayerOnlineResult)(nil),  // 6: framework.PlayerOnlineResult
	(*PlayerOfflineResult)(nil), // 7: framework.PlayerOfflineResult
	(*PlayerQueryResult)(nil),   // 8: framework.PlayerQueryResult
	(*HeartbeatResult)(nil),     // 9: framework.HeartbeatResult
	(*KickPlayer)(nil),          // 10: framework.KickPlayer
	(*BroadcastMessage)(nil),    // 11: framework.BroadcastMessage
}
var file_center_proto_depIdxs = []int32{
	2,  // 0: framework.CenterRequest.player_online:type_name -> framework.PlayerOnline
	3,  // 1: framework.CenterRequest.player_offline:type_name -> framework.PlayerOffline
	4,  // 2: framework.CenterRequest.player_query:type_name -> framework.PlayerQuery
	5,  // 3: framework.CenterRequest.heartbeat:type_name -> framework.Heartbeat
	6,  // 4: framework.CenterResponse.online_result:type_name -> framework.PlayerOnlineResult
	7,  // 5: framework.CenterResponse.offline_result:type_name -> framework.PlayerOfflineResult
	8,  // 6: framework.CenterResponse.query_result:type_name -> framework.PlayerQueryResult
	9,  // 7: framework.CenterResponse.heartbeat_result:type_name -> framework.HeartbeatResult
	10, // 8: framework.CenterResponse.kick_player:type_name -> framework.KickPlayer
	11, // 9: framework.CenterResponse.broadcast:type_name -> framework.BroadcastMessage
	0,  // 10: framework.CenterService.Stream:input_type -> framework.CenterRequest
	1,  // 11: framework.CenterService.Stream:output_type -> framework.CenterResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_center_proto_init() }
func file_center_proto_init() {
	if File_center_proto != nil {
		return
	}
	file_center_proto_msgTypes[0].OneofWrappers = []any{
		(*CenterRequest_PlayerOnline)(nil),
		(*CenterRequest_PlayerOffline)(nil),
		(*CenterRequest_PlayerQuery)(nil),
		(*CenterRequest_Heartbeat)(nil),
	}
	file_center_proto_msgTypes[1].OneofWrappers = []any{
		(*CenterResponse_OnlineResult)(nil),
		(*CenterResponse_OfflineResult)(nil),
		(*CenterResponse_QueryResult)(nil),
		(*CenterResponse_HeartbeatResult)(nil),
		(*CenterResponse_KickPlayer)(nil),
		(*CenterResponse_Broadcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_center_proto_rawDesc), len(file_center_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_center_proto_goTypes,
		DependencyIndexes: file_center_proto_depIdxs,
		MessageInfos:      file_center_proto_msgTypes,
	}.Build()
	File_center_proto = out.File
	file_center_proto_goTypes = nil
	file_center_proto_depIdxs = nil
}
