// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: douyin.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_douyin_proto protoreflect.FileDescriptor

const file_douyin_proto_rawDesc = "" +
	"\n" +
	"\fdouyin.proto\x12\tframework\x1a\x11douyin_type.proto2\xc7\x02\n" +
	"\x11DouyinGameService\x12N\n" +
	"\rHandleComment\x12\x1d.framework.DouyinCommentEvent\x1a\x1e.framework.DouyinEventResponse\x12H\n" +
	"\n" +
	"HandleGift\x12\x1a.framework.DouyinGiftEvent\x1a\x1e.framework.DouyinEventResponse\x12H\n" +
	"\n" +
	"HandleLike\x12\x1a.framework.DouyinLikeEvent\x1a\x1e.framework.DouyinEventResponse\x12N\n" +
	"\rHandleFanClub\x12\x1d.framework.DouyinFanClubEvent\x1a\x1e.framework.DouyinEventResponseB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var file_douyin_proto_goTypes = []any{
	(*DouyinCommentEvent)(nil),  // 0: framework.DouyinCommentEvent
	(*DouyinGiftEvent)(nil),     // 1: framework.DouyinGiftEvent
	(*DouyinLikeEvent)(nil),     // 2: framework.DouyinLikeEvent
	(*DouyinFanClubEvent)(nil),  // 3: framework.DouyinFanClubEvent
	(*DouyinEventResponse)(nil), // 4: framework.DouyinEventResponse
}
var file_douyin_proto_depIdxs = []int32{
	0, // 0: framework.DouyinGameService.HandleComment:input_type -> framework.DouyinCommentEvent
	1, // 1: framework.DouyinGameService.HandleGift:input_type -> framework.DouyinGiftEvent
	2, // 2: framework.DouyinGameService.HandleLike:input_type -> framework.DouyinLikeEvent
	3, // 3: framework.DouyinGameService.HandleFanClub:input_type -> framework.DouyinFanClubEvent
	4, // 4: framework.DouyinGameService.HandleComment:output_type -> framework.DouyinEventResponse
	4, // 5: framework.DouyinGameService.HandleGift:output_type -> framework.DouyinEventResponse
	4, // 6: framework.DouyinGameService.HandleLike:output_type -> framework.DouyinEventResponse
	4, // 7: framework.DouyinGameService.HandleFanClub:output_type -> framework.DouyinEventResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_douyin_proto_init() }
func file_douyin_proto_init() {
	if File_douyin_proto != nil {
		return
	}
	file_douyin_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_douyin_proto_rawDesc), len(file_douyin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_douyin_proto_goTypes,
		DependencyIndexes: file_douyin_proto_depIdxs,
	}.Build()
	File_douyin_proto = out.File
	file_douyin_proto_goTypes = nil
	file_douyin_proto_depIdxs = nil
}
