// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: douyin_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DouyinCommentEvent 抖音评论事件
type DouyinCommentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                // 消息ID
	SecOpenid     string                 `protobuf:"bytes,2,opt,name=sec_openid,json=secOpenid,proto3" json:"sec_openid,omitempty"`    // 用户openid
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                         // 评论内容
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`    // 头像URL
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`                       // 昵称
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 时间戳
	AnchorUuid    string                 `protobuf:"bytes,7,opt,name=anchor_uuid,json=anchorUuid,proto3" json:"anchor_uuid,omitempty"` // 主播UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DouyinCommentEvent) Reset() {
	*x = DouyinCommentEvent{}
	mi := &file_douyin_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DouyinCommentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinCommentEvent) ProtoMessage() {}

func (x *DouyinCommentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinCommentEvent.ProtoReflect.Descriptor instead.
func (*DouyinCommentEvent) Descriptor() ([]byte, []int) {
	return file_douyin_type_proto_rawDescGZIP(), []int{0}
}

func (x *DouyinCommentEvent) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DouyinCommentEvent) GetSecOpenid() string {
	if x != nil {
		return x.SecOpenid
	}
	return ""
}

func (x *DouyinCommentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DouyinCommentEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DouyinCommentEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DouyinCommentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DouyinCommentEvent) GetAnchorUuid() string {
	if x != nil {
		return x.AnchorUuid
	}
	return ""
}

// DouyinGiftEvent 抖音礼物事件
type DouyinGiftEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                // 消息ID
	SecOpenid      string                 `protobuf:"bytes,2,opt,name=sec_openid,json=secOpenid,proto3" json:"sec_openid,omitempty"`                    // 用户openid
	SecGiftId      string                 `protobuf:"bytes,3,opt,name=sec_gift_id,json=secGiftId,proto3" json:"sec_gift_id,omitempty"`                  // 礼物ID
	GiftNum        uint32                 `protobuf:"varint,4,opt,name=gift_num,json=giftNum,proto3" json:"gift_num,omitempty"`                         // 礼物数量
	GiftValue      uint32                 `protobuf:"varint,5,opt,name=gift_value,json=giftValue,proto3" json:"gift_value,omitempty"`                   // 礼物价值(抖币)
	AvatarUrl      string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                    // 头像URL
	Nickname       string                 `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`                                       // 昵称
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // 时间戳
	SecMagicGiftId string                 `protobuf:"bytes,9,opt,name=sec_magic_gift_id,json=secMagicGiftId,proto3" json:"sec_magic_gift_id,omitempty"` // 幸运魔方礼物ID
	Test           bool                   `protobuf:"varint,10,opt,name=test,proto3" json:"test,omitempty"`                                             // 是否测试数据
	AnchorUuid     string                 `protobuf:"bytes,11,opt,name=anchor_uuid,json=anchorUuid,proto3" json:"anchor_uuid,omitempty"`                // 主播UUID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DouyinGiftEvent) Reset() {
	*x = DouyinGiftEvent{}
	mi := &file_douyin_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DouyinGiftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGiftEvent) ProtoMessage() {}

func (x *DouyinGiftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGiftEvent.ProtoReflect.Descriptor instead.
func (*DouyinGiftEvent) Descriptor() ([]byte, []int) {
	return file_douyin_type_proto_rawDescGZIP(), []int{1}
}

func (x *DouyinGiftEvent) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DouyinGiftEvent) GetSecOpenid() string {
	if x != nil {
		return x.SecOpenid
	}
	return ""
}

func (x *DouyinGiftEvent) GetSecGiftId() string {
	if x != nil {
		return x.SecGiftId
	}
	return ""
}

func (x *DouyinGiftEvent) GetGiftNum() uint32 {
	if x != nil {
		return x.GiftNum
	}
	return 0
}

func (x *DouyinGiftEvent) GetGiftValue() uint32 {
	if x != nil {
		return x.GiftValue
	}
	return 0
}

func (x *DouyinGiftEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DouyinGiftEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DouyinGiftEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DouyinGiftEvent) GetSecMagicGiftId() string {
	if x != nil {
		return x.SecMagicGiftId
	}
	return ""
}

func (x *DouyinGiftEvent) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

func (x *DouyinGiftEvent) GetAnchorUuid() string {
	if x != nil {
		return x.AnchorUuid
	}
	return ""
}

// DouyinLikeEvent 抖音点赞事件
type DouyinLikeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                // 消息ID
	SecOpenid     string                 `protobuf:"bytes,2,opt,name=sec_openid,json=secOpenid,proto3" json:"sec_openid,omitempty"`    // 用户openid
	LikeNum       uint32                 `protobuf:"varint,3,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`         // 点赞数量
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`    // 头像URL
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`                       // 昵称
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 时间戳
	AnchorUuid    string                 `protobuf:"bytes,7,opt,name=anchor_uuid,json=anchorUuid,proto3" json:"anchor_uuid,omitempty"` // 主播UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DouyinLikeEvent) Reset() {
	*x = DouyinLikeEvent{}
	mi := &file_douyin_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DouyinLikeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinLikeEvent) ProtoMessage() {}

func (x *DouyinLikeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinLikeEvent.ProtoReflect.Descriptor instead.
func (*DouyinLikeEvent) Descriptor() ([]byte, []int) {
	return file_douyin_type_proto_rawDescGZIP(), []int{2}
}

func (x *DouyinLikeEvent) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DouyinLikeEvent) GetSecOpenid() string {
	if x != nil {
		return x.SecOpenid
	}
	return ""
}

func (x *DouyinLikeEvent) GetLikeNum() uint32 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *DouyinLikeEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DouyinLikeEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DouyinLikeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DouyinLikeEvent) GetAnchorUuid() string {
	if x != nil {
		return x.AnchorUuid
	}
	return ""
}

// DouyinFanClubEvent 抖音粉丝团事件
type DouyinFanClubEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MsgId              string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                           // 消息ID
	SecOpenid          string                 `protobuf:"bytes,2,opt,name=sec_openid,json=secOpenid,proto3" json:"sec_openid,omitempty"`                               // 用户openid
	AvatarUrl          string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                               // 头像URL
	Nickname           string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                  // 昵称
	Timestamp          int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                               // 时间戳
	FansclubReasonType uint32                 `protobuf:"varint,6,opt,name=fansclub_reason_type,json=fansclubReasonType,proto3" json:"fansclub_reason_type,omitempty"` // 粉丝团变更原因类型
	FansclubLevel      uint32                 `protobuf:"varint,7,opt,name=fansclub_level,json=fansclubLevel,proto3" json:"fansclub_level,omitempty"`                  // 粉丝团等级
	AnchorUuid         string                 `protobuf:"bytes,8,opt,name=anchor_uuid,json=anchorUuid,proto3" json:"anchor_uuid,omitempty"`                            // 主播UUID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DouyinFanClubEvent) Reset() {
	*x = DouyinFanClubEvent{}
	mi := &file_douyin_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DouyinFanClubEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinFanClubEvent) ProtoMessage() {}

func (x *DouyinFanClubEvent) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinFanClubEvent.ProtoReflect.Descriptor instead.
func (*DouyinFanClubEvent) Descriptor() ([]byte, []int) {
	return file_douyin_type_proto_rawDescGZIP(), []int{3}
}

func (x *DouyinFanClubEvent) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DouyinFanClubEvent) GetSecOpenid() string {
	if x != nil {
		return x.SecOpenid
	}
	return ""
}

func (x *DouyinFanClubEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DouyinFanClubEvent) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DouyinFanClubEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DouyinFanClubEvent) GetFansclubReasonType() uint32 {
	if x != nil {
		return x.FansclubReasonType
	}
	return 0
}

func (x *DouyinFanClubEvent) GetFansclubLevel() uint32 {
	if x != nil {
		return x.FansclubLevel
	}
	return 0
}

func (x *DouyinFanClubEvent) GetAnchorUuid() string {
	if x != nil {
		return x.AnchorUuid
	}
	return ""
}

// DouyinEventResponse 抖音事件统一响应
type DouyinEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码 0-成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DouyinEventResponse) Reset() {
	*x = DouyinEventResponse{}
	mi := &file_douyin_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DouyinEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinEventResponse) ProtoMessage() {}

func (x *DouyinEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinEventResponse.ProtoReflect.Descriptor instead.
func (*DouyinEventResponse) Descriptor() ([]byte, []int) {
	return file_douyin_type_proto_rawDescGZIP(), []int{4}
}

func (x *DouyinEventResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_douyin_type_proto protoreflect.FileDescriptor

const file_douyin_type_proto_rawDesc = "" +
	"\n" +
	"\x11douyin_type.proto\x12\tframework\"\xde\x01\n" +
	"\x12DouyinCommentEvent\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1d\n" +
	"\n" +
	"sec_openid\x18\x02 \x01(\tR\tsecOpenid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vanchor_uuid\x18\a \x01(\tR\n" +
	"anchorUuid\"\xda\x02\n" +
	"\x0fDouyinGiftEvent\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1d\n" +
	"\n" +
	"sec_openid\x18\x02 \x01(\tR\tsecOpenid\x12\x1e\n" +
	"\vsec_gift_id\x18\x03 \x01(\tR\tsecGiftId\x12\x19\n" +
	"\bgift_num\x18\x04 \x01(\rR\agiftNum\x12\x1d\n" +
	"\n" +
	"gift_value\x18\x05 \x01(\rR\tgiftValue\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12)\n" +
	"\x11sec_magic_gift_id\x18\t \x01(\tR\x0esecMagicGiftId\x12\x12\n" +
	"\x04test\x18\n" +
	" \x01(\bR\x04test\x12\x1f\n" +
	"\vanchor_uuid\x18\v \x01(\tR\n" +
	"anchorUuid\"\xdc\x01\n" +
	"\x0fDouyinLikeEvent\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1d\n" +
	"\n" +
	"sec_openid\x18\x02 \x01(\tR\tsecOpenid\x12\x19\n" +
	"\blike_num\x18\x03 \x01(\rR\alikeNum\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vanchor_uuid\x18\a \x01(\tR\n" +
	"anchorUuid\"\x9d\x02\n" +
	"\x12DouyinFanClubEvent\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1d\n" +
	"\n" +
	"sec_openid\x18\x02 \x01(\tR\tsecOpenid\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x120\n" +
	"\x14fansclub_reason_type\x18\x06 \x01(\rR\x12fansclubReasonType\x12%\n" +
	"\x0efansclub_level\x18\a \x01(\rR\rfansclubLevel\x12\x1f\n" +
	"\vanchor_uuid\x18\b \x01(\tR\n" +
	"anchorUuid\")\n" +
	"\x13DouyinEventResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_douyin_type_proto_rawDescOnce sync.Once
	file_douyin_type_proto_rawDescData []byte
)

func file_douyin_type_proto_rawDescGZIP() []byte {
	file_douyin_type_proto_rawDescOnce.Do(func() {
		file_douyin_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_douyin_type_proto_rawDesc), len(file_douyin_type_proto_rawDesc)))
	})
	return file_douyin_type_proto_rawDescData
}

var file_douyin_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_douyin_type_proto_goTypes = []any{
	(*DouyinCommentEvent)(nil),  // 0: framework.DouyinCommentEvent
	(*DouyinGiftEvent)(nil),     // 1: framework.DouyinGiftEvent
	(*DouyinLikeEvent)(nil),     // 2: framework.DouyinLikeEvent
	(*DouyinFanClubEvent)(nil),  // 3: framework.DouyinFanClubEvent
	(*DouyinEventResponse)(nil), // 4: framework.DouyinEventResponse
}
var file_douyin_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_douyin_type_proto_init() }
func file_douyin_type_proto_init() {
	if File_douyin_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_douyin_type_proto_rawDesc), len(file_douyin_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_douyin_type_proto_goTypes,
		DependencyIndexes: file_douyin_type_proto_depIdxs,
		MessageInfos:      file_douyin_type_proto_msgTypes,
	}.Build()
	File_douyin_type_proto = out.File
	file_douyin_type_proto_goTypes = nil
	file_douyin_type_proto_depIdxs = nil
}
