// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: douyin.proto

package framework

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DouyinGameService_HandleComment_FullMethodName = "/framework.DouyinGameService/HandleComment"
	DouyinGameService_HandleGift_FullMethodName    = "/framework.DouyinGameService/HandleGift"
	DouyinGameService_HandleLike_FullMethodName    = "/framework.DouyinGameService/HandleLike"
	DouyinGameService_HandleFanClub_FullMethodName = "/framework.DouyinGameService/HandleFanClub"
)

// DouyinGameServiceClient is the client API for DouyinGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DouyinGameService Live 调用 Game 处理抖音事件的服务
type DouyinGameServiceClient interface {
	// HandleComment 处理评论事件
	HandleComment(ctx context.Context, in *DouyinCommentEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error)
	// HandleGift 处理礼物事件
	HandleGift(ctx context.Context, in *DouyinGiftEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error)
	// HandleLike 处理点赞事件
	HandleLike(ctx context.Context, in *DouyinLikeEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error)
	// HandleFanClub 处理粉丝团事件
	HandleFanClub(ctx context.Context, in *DouyinFanClubEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error)
}

type douyinGameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDouyinGameServiceClient(cc grpc.ClientConnInterface) DouyinGameServiceClient {
	return &douyinGameServiceClient{cc}
}

func (c *douyinGameServiceClient) HandleComment(ctx context.Context, in *DouyinCommentEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinEventResponse)
	err := c.cc.Invoke(ctx, DouyinGameService_HandleComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinGameServiceClient) HandleGift(ctx context.Context, in *DouyinGiftEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinEventResponse)
	err := c.cc.Invoke(ctx, DouyinGameService_HandleGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinGameServiceClient) HandleLike(ctx context.Context, in *DouyinLikeEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinEventResponse)
	err := c.cc.Invoke(ctx, DouyinGameService_HandleLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinGameServiceClient) HandleFanClub(ctx context.Context, in *DouyinFanClubEvent, opts ...grpc.CallOption) (*DouyinEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DouyinEventResponse)
	err := c.cc.Invoke(ctx, DouyinGameService_HandleFanClub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DouyinGameServiceServer is the server API for DouyinGameService service.
// All implementations must embed UnimplementedDouyinGameServiceServer
// for forward compatibility.
//
// DouyinGameService Live 调用 Game 处理抖音事件的服务
type DouyinGameServiceServer interface {
	// HandleComment 处理评论事件
	HandleComment(context.Context, *DouyinCommentEvent) (*DouyinEventResponse, error)
	// HandleGift 处理礼物事件
	HandleGift(context.Context, *DouyinGiftEvent) (*DouyinEventResponse, error)
	// HandleLike 处理点赞事件
	HandleLike(context.Context, *DouyinLikeEvent) (*DouyinEventResponse, error)
	// HandleFanClub 处理粉丝团事件
	HandleFanClub(context.Context, *DouyinFanClubEvent) (*DouyinEventResponse, error)
	mustEmbedUnimplementedDouyinGameServiceServer()
}

// UnimplementedDouyinGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDouyinGameServiceServer struct{}

func (UnimplementedDouyinGameServiceServer) HandleComment(context.Context, *DouyinCommentEvent) (*DouyinEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleComment not implemented")
}
func (UnimplementedDouyinGameServiceServer) HandleGift(context.Context, *DouyinGiftEvent) (*DouyinEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGift not implemented")
}
func (UnimplementedDouyinGameServiceServer) HandleLike(context.Context, *DouyinLikeEvent) (*DouyinEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleLike not implemented")
}
func (UnimplementedDouyinGameServiceServer) HandleFanClub(context.Context, *DouyinFanClubEvent) (*DouyinEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFanClub not implemented")
}
func (UnimplementedDouyinGameServiceServer) mustEmbedUnimplementedDouyinGameServiceServer() {}
func (UnimplementedDouyinGameServiceServer) testEmbeddedByValue()                           {}

// UnsafeDouyinGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DouyinGameServiceServer will
// result in compilation errors.
type UnsafeDouyinGameServiceServer interface {
	mustEmbedUnimplementedDouyinGameServiceServer()
}

func RegisterDouyinGameServiceServer(s grpc.ServiceRegistrar, srv DouyinGameServiceServer) {
	// If the following call panics, it indicates UnimplementedDouyinGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DouyinGameService_ServiceDesc, srv)
}

func _DouyinGameService_HandleComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinGameServiceServer).HandleComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinGameService_HandleComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinGameServiceServer).HandleComment(ctx, req.(*DouyinCommentEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinGameService_HandleGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinGiftEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinGameServiceServer).HandleGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinGameService_HandleGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinGameServiceServer).HandleGift(ctx, req.(*DouyinGiftEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinGameService_HandleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinLikeEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinGameServiceServer).HandleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinGameService_HandleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinGameServiceServer).HandleLike(ctx, req.(*DouyinLikeEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinGameService_HandleFanClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinFanClubEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinGameServiceServer).HandleFanClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinGameService_HandleFanClub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinGameServiceServer).HandleFanClub(ctx, req.(*DouyinFanClubEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// DouyinGameService_ServiceDesc is the grpc.ServiceDesc for DouyinGameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DouyinGameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "framework.DouyinGameService",
	HandlerType: (*DouyinGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleComment",
			Handler:    _DouyinGameService_HandleComment_Handler,
		},
		{
			MethodName: "HandleGift",
			Handler:    _DouyinGameService_HandleGift_Handler,
		},
		{
			MethodName: "HandleLike",
			Handler:    _DouyinGameService_HandleLike_Handler,
		},
		{
			MethodName: "HandleFanClub",
			Handler:    _DouyinGameService_HandleFanClub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "douyin.proto",
}
