// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: forward.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForwardMessage 针对单一玩家的转发包装
// 用于 Gateway 与 Game 之间的内部明文通信
type ForwardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家唯一 ID (UUID)
	UserUuid string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// 原始业务协议号 (OpCode)
	OpCode uint32 `protobuf:"varint,2,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	// 原始业务明文载荷 (Payload)
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessage) Reset() {
	*x = ForwardMessage{}
	mi := &file_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessage) ProtoMessage() {}

func (x *ForwardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessage.ProtoReflect.Descriptor instead.
func (*ForwardMessage) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardMessage) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ForwardMessage) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *ForwardMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ForwardBroadcastMessage 针对全网关在线玩家的广播包装
// 网关收到后将发送给该节点下的所有客户端
type ForwardBroadcastMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原始业务协议号 (OpCode)
	OpCode uint32 `protobuf:"varint,1,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	// 原始业务明文载荷 (Payload)
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardBroadcastMessage) Reset() {
	*x = ForwardBroadcastMessage{}
	mi := &file_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardBroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardBroadcastMessage) ProtoMessage() {}

func (x *ForwardBroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardBroadcastMessage.ProtoReflect.Descriptor instead.
func (*ForwardBroadcastMessage) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardBroadcastMessage) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *ForwardBroadcastMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_forward_proto protoreflect.FileDescriptor

const file_forward_proto_rawDesc = "" +
	"\n" +
	"\rforward.proto\x12\tframework\"`\n" +
	"\x0eForwardMessage\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x17\n" +
	"\aop_code\x18\x02 \x01(\rR\x06opCode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"L\n" +
	"\x17ForwardBroadcastMessage\x12\x17\n" +
	"\aop_code\x18\x01 \x01(\rR\x06opCode\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData []byte
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)))
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forward_proto_goTypes = []any{
	(*ForwardMessage)(nil),          // 0: framework.ForwardMessage
	(*ForwardBroadcastMessage)(nil), // 1: framework.ForwardBroadcastMessage
}
var file_forward_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
