// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: internal_node.proto

package framework

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalNodeService_SyncUserAction_FullMethodName = "/framework.InternalNodeService/SyncUserAction"
	InternalNodeService_SyncUserReward_FullMethodName = "/framework.InternalNodeService/SyncUserReward"
)

// InternalNodeServiceClient is the client API for InternalNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalNodeService Game 节点间内部通信服务
type InternalNodeServiceClient interface {
	// SyncUserAction [玩家节点 -> 主播节点]
	// 场景：玩家在分配到的 Game 节点扣费后，通知主播所在的 Game 节点更新玩法状态
	SyncUserAction(ctx context.Context, in *SyncUserActionReq, opts ...grpc.CallOption) (*SyncUserActionRes, error)
	// SyncUserReward [主播节点 -> 玩家节点]
	// 场景：主播房间所在的 Game 节点产生结算后，通知玩家所在的 Game 节点增加资产/经验
	SyncUserReward(ctx context.Context, in *SyncUserRewardReq, opts ...grpc.CallOption) (*SyncUserRewardRes, error)
}

type internalNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalNodeServiceClient(cc grpc.ClientConnInterface) InternalNodeServiceClient {
	return &internalNodeServiceClient{cc}
}

func (c *internalNodeServiceClient) SyncUserAction(ctx context.Context, in *SyncUserActionReq, opts ...grpc.CallOption) (*SyncUserActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserActionRes)
	err := c.cc.Invoke(ctx, InternalNodeService_SyncUserAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalNodeServiceClient) SyncUserReward(ctx context.Context, in *SyncUserRewardReq, opts ...grpc.CallOption) (*SyncUserRewardRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserRewardRes)
	err := c.cc.Invoke(ctx, InternalNodeService_SyncUserReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalNodeServiceServer is the server API for InternalNodeService service.
// All implementations must embed UnimplementedInternalNodeServiceServer
// for forward compatibility.
//
// InternalNodeService Game 节点间内部通信服务
type InternalNodeServiceServer interface {
	// SyncUserAction [玩家节点 -> 主播节点]
	// 场景：玩家在分配到的 Game 节点扣费后，通知主播所在的 Game 节点更新玩法状态
	SyncUserAction(context.Context, *SyncUserActionReq) (*SyncUserActionRes, error)
	// SyncUserReward [主播节点 -> 玩家节点]
	// 场景：主播房间所在的 Game 节点产生结算后，通知玩家所在的 Game 节点增加资产/经验
	SyncUserReward(context.Context, *SyncUserRewardReq) (*SyncUserRewardRes, error)
	mustEmbedUnimplementedInternalNodeServiceServer()
}

// UnimplementedInternalNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalNodeServiceServer struct{}

func (UnimplementedInternalNodeServiceServer) SyncUserAction(context.Context, *SyncUserActionReq) (*SyncUserActionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUserAction not implemented")
}
func (UnimplementedInternalNodeServiceServer) SyncUserReward(context.Context, *SyncUserRewardReq) (*SyncUserRewardRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUserReward not implemented")
}
func (UnimplementedInternalNodeServiceServer) mustEmbedUnimplementedInternalNodeServiceServer() {}
func (UnimplementedInternalNodeServiceServer) testEmbeddedByValue()                             {}

// UnsafeInternalNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalNodeServiceServer will
// result in compilation errors.
type UnsafeInternalNodeServiceServer interface {
	mustEmbedUnimplementedInternalNodeServiceServer()
}

func RegisterInternalNodeServiceServer(s grpc.ServiceRegistrar, srv InternalNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalNodeService_ServiceDesc, srv)
}

func _InternalNodeService_SyncUserAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNodeServiceServer).SyncUserAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNodeService_SyncUserAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNodeServiceServer).SyncUserAction(ctx, req.(*SyncUserActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalNodeService_SyncUserReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserRewardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNodeServiceServer).SyncUserReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNodeService_SyncUserReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNodeServiceServer).SyncUserReward(ctx, req.(*SyncUserRewardReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalNodeService_ServiceDesc is the grpc.ServiceDesc for InternalNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "framework.InternalNodeService",
	HandlerType: (*InternalNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncUserAction",
			Handler:    _InternalNodeService_SyncUserAction_Handler,
		},
		{
			MethodName: "SyncUserReward",
			Handler:    _InternalNodeService_SyncUserReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal_node.proto",
}
