// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: internal_push.proto

package framework

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalPushService_PushToUser_FullMethodName      = "/framework.InternalPushService/PushToUser"
	InternalPushService_MulticastToRoom_FullMethodName = "/framework.InternalPushService/MulticastToRoom"
)

// InternalPushServiceClient is the client API for InternalPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalPushService 跨服下行推送服务
type InternalPushServiceClient interface {
	// PushToUser [Game -> Gateway]
	// 推送给指定在线用户
	PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserRes, error)
	// MulticastToRoom [Game -> Gateway]
	// 组播给该网关下属于指定房间的所有玩家/主播
	MulticastToRoom(ctx context.Context, in *MulticastToRoomReq, opts ...grpc.CallOption) (*MulticastToRoomRes, error)
}

type internalPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalPushServiceClient(cc grpc.ClientConnInterface) InternalPushServiceClient {
	return &internalPushServiceClient{cc}
}

func (c *internalPushServiceClient) PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToUserRes)
	err := c.cc.Invoke(ctx, InternalPushService_PushToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalPushServiceClient) MulticastToRoom(ctx context.Context, in *MulticastToRoomReq, opts ...grpc.CallOption) (*MulticastToRoomRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MulticastToRoomRes)
	err := c.cc.Invoke(ctx, InternalPushService_MulticastToRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalPushServiceServer is the server API for InternalPushService service.
// All implementations must embed UnimplementedInternalPushServiceServer
// for forward compatibility.
//
// InternalPushService 跨服下行推送服务
type InternalPushServiceServer interface {
	// PushToUser [Game -> Gateway]
	// 推送给指定在线用户
	PushToUser(context.Context, *PushToUserReq) (*PushToUserRes, error)
	// MulticastToRoom [Game -> Gateway]
	// 组播给该网关下属于指定房间的所有玩家/主播
	MulticastToRoom(context.Context, *MulticastToRoomReq) (*MulticastToRoomRes, error)
	mustEmbedUnimplementedInternalPushServiceServer()
}

// UnimplementedInternalPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalPushServiceServer struct{}

func (UnimplementedInternalPushServiceServer) PushToUser(context.Context, *PushToUserReq) (*PushToUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToUser not implemented")
}
func (UnimplementedInternalPushServiceServer) MulticastToRoom(context.Context, *MulticastToRoomReq) (*MulticastToRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MulticastToRoom not implemented")
}
func (UnimplementedInternalPushServiceServer) mustEmbedUnimplementedInternalPushServiceServer() {}
func (UnimplementedInternalPushServiceServer) testEmbeddedByValue()                             {}

// UnsafeInternalPushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalPushServiceServer will
// result in compilation errors.
type UnsafeInternalPushServiceServer interface {
	mustEmbedUnimplementedInternalPushServiceServer()
}

func RegisterInternalPushServiceServer(s grpc.ServiceRegistrar, srv InternalPushServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalPushService_ServiceDesc, srv)
}

func _InternalPushService_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).PushToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_PushToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).PushToUser(ctx, req.(*PushToUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalPushService_MulticastToRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MulticastToRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).MulticastToRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_MulticastToRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).MulticastToRoom(ctx, req.(*MulticastToRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalPushService_ServiceDesc is the grpc.ServiceDesc for InternalPushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalPushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "framework.InternalPushService",
	HandlerType: (*InternalPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToUser",
			Handler:    _InternalPushService_PushToUser_Handler,
		},
		{
			MethodName: "MulticastToRoom",
			Handler:    _InternalPushService_MulticastToRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal_push.proto",
}
