// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal_node.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncUserActionReq 同步玩家操作请求
type SyncUserActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                        // 玩家UID
	AnchorOpenId  string                 `protobuf:"bytes,2,opt,name=anchor_open_id,json=anchorOpenId,proto3" json:"anchor_open_id,omitempty"` // 目标主播ID
	ActionType    uint32                 `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`        // 动作类型
	ActionData    []byte                 `protobuf:"bytes,4,opt,name=action_data,json=actionData,proto3" json:"action_data,omitempty"`         // 业务序列化数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserActionReq) Reset() {
	*x = SyncUserActionReq{}
	mi := &file_internal_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserActionReq) ProtoMessage() {}

func (x *SyncUserActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserActionReq.ProtoReflect.Descriptor instead.
func (*SyncUserActionReq) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_rawDescGZIP(), []int{0}
}

func (x *SyncUserActionReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncUserActionReq) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *SyncUserActionReq) GetActionType() uint32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *SyncUserActionReq) GetActionData() []byte {
	if x != nil {
		return x.ActionData
	}
	return nil
}

// SyncUserActionRes 同步玩家操作响应
type SyncUserActionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"` // 错误码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserActionRes) Reset() {
	*x = SyncUserActionRes{}
	mi := &file_internal_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserActionRes) ProtoMessage() {}

func (x *SyncUserActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserActionRes.ProtoReflect.Descriptor instead.
func (*SyncUserActionRes) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_rawDescGZIP(), []int{1}
}

func (x *SyncUserActionRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

// SyncUserRewardReq 同步玩家奖励请求
type SyncUserRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                 // 玩家UID
	RewardType    uint32                 `protobuf:"varint,2,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"` // 奖励类型
	RewardData    []byte                 `protobuf:"bytes,3,opt,name=reward_data,json=rewardData,proto3" json:"reward_data,omitempty"`  // 业务序列化数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserRewardReq) Reset() {
	*x = SyncUserRewardReq{}
	mi := &file_internal_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserRewardReq) ProtoMessage() {}

func (x *SyncUserRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserRewardReq.ProtoReflect.Descriptor instead.
func (*SyncUserRewardReq) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_rawDescGZIP(), []int{2}
}

func (x *SyncUserRewardReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncUserRewardReq) GetRewardType() uint32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *SyncUserRewardReq) GetRewardData() []byte {
	if x != nil {
		return x.RewardData
	}
	return nil
}

// SyncUserRewardRes 同步玩家奖励响应
type SyncUserRewardRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"` // 错误码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserRewardRes) Reset() {
	*x = SyncUserRewardRes{}
	mi := &file_internal_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserRewardRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserRewardRes) ProtoMessage() {}

func (x *SyncUserRewardRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserRewardRes.ProtoReflect.Descriptor instead.
func (*SyncUserRewardRes) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_rawDescGZIP(), []int{3}
}

func (x *SyncUserRewardRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

var File_internal_node_proto protoreflect.FileDescriptor

const file_internal_node_proto_rawDesc = "" +
	"\n" +
	"\x13internal_node.proto\x12\tframework\x1a\x0eerr_code.proto\"\x8d\x01\n" +
	"\x11SyncUserActionReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12$\n" +
	"\x0eanchor_open_id\x18\x02 \x01(\tR\fanchorOpenId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\rR\n" +
	"actionType\x12\x1f\n" +
	"\vaction_data\x18\x04 \x01(\fR\n" +
	"actionData\";\n" +
	"\x11SyncUserActionRes\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code\"g\n" +
	"\x11SyncUserRewardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x1f\n" +
	"\vreward_type\x18\x02 \x01(\rR\n" +
	"rewardType\x12\x1f\n" +
	"\vreward_data\x18\x03 \x01(\fR\n" +
	"rewardData\";\n" +
	"\x11SyncUserRewardRes\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code2\xb1\x01\n" +
	"\x13InternalNodeService\x12L\n" +
	"\x0eSyncUserAction\x12\x1c.framework.SyncUserActionReq\x1a\x1c.framework.SyncUserActionRes\x12L\n" +
	"\x0eSyncUserReward\x12\x1c.framework.SyncUserRewardReq\x1a\x1c.framework.SyncUserRewardResB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_internal_node_proto_rawDescOnce sync.Once
	file_internal_node_proto_rawDescData []byte
)

func file_internal_node_proto_rawDescGZIP() []byte {
	file_internal_node_proto_rawDescOnce.Do(func() {
		file_internal_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_node_proto_rawDesc), len(file_internal_node_proto_rawDesc)))
	})
	return file_internal_node_proto_rawDescData
}

var file_internal_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_node_proto_goTypes = []any{
	(*SyncUserActionReq)(nil), // 0: framework.SyncUserActionReq
	(*SyncUserActionRes)(nil), // 1: framework.SyncUserActionRes
	(*SyncUserRewardReq)(nil), // 2: framework.SyncUserRewardReq
	(*SyncUserRewardRes)(nil), // 3: framework.SyncUserRewardRes
	(ErrCode)(0),              // 4: framework.ErrCode
}
var file_internal_node_proto_depIdxs = []int32{
	4, // 0: framework.SyncUserActionRes.code:type_name -> framework.ErrCode
	4, // 1: framework.SyncUserRewardRes.code:type_name -> framework.ErrCode
	0, // 2: framework.InternalNodeService.SyncUserAction:input_type -> framework.SyncUserActionReq
	2, // 3: framework.InternalNodeService.SyncUserReward:input_type -> framework.SyncUserRewardReq
	1, // 4: framework.InternalNodeService.SyncUserAction:output_type -> framework.SyncUserActionRes
	3, // 5: framework.InternalNodeService.SyncUserReward:output_type -> framework.SyncUserRewardRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_node_proto_init() }
func file_internal_node_proto_init() {
	if File_internal_node_proto != nil {
		return
	}
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_node_proto_rawDesc), len(file_internal_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_node_proto_goTypes,
		DependencyIndexes: file_internal_node_proto_depIdxs,
		MessageInfos:      file_internal_node_proto_msgTypes,
	}.Build()
	File_internal_node_proto = out.File
	file_internal_node_proto_goTypes = nil
	file_internal_node_proto_depIdxs = nil
}
