// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal_push.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushToUserReq 单播请求
type PushToUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                     // 目标用户UID
	OpCode        uint32                 `protobuf:"varint,2,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"` // 业务协议号
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`              // 业务序列化消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUserReq) Reset() {
	*x = PushToUserReq{}
	mi := &file_internal_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserReq) ProtoMessage() {}

func (x *PushToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserReq.ProtoReflect.Descriptor instead.
func (*PushToUserReq) Descriptor() ([]byte, []int) {
	return file_internal_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushToUserReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PushToUserReq) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *PushToUserReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PushToUserRes 单播响应
type PushToUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"` // 错误码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUserRes) Reset() {
	*x = PushToUserRes{}
	mi := &file_internal_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserRes) ProtoMessage() {}

func (x *PushToUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserRes.ProtoReflect.Descriptor instead.
func (*PushToUserRes) Descriptor() ([]byte, []int) {
	return file_internal_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushToUserRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

// MulticastToRoomReq 组播请求
type MulticastToRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnchorOpenId  string                 `protobuf:"bytes,1,opt,name=anchor_open_id,json=anchorOpenId,proto3" json:"anchor_open_id,omitempty"` // 直播间主播ID
	OpCode        uint32                 `protobuf:"varint,2,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`                    // 业务协议号
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                 // 业务序列化消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MulticastToRoomReq) Reset() {
	*x = MulticastToRoomReq{}
	mi := &file_internal_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastToRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastToRoomReq) ProtoMessage() {}

func (x *MulticastToRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastToRoomReq.ProtoReflect.Descriptor instead.
func (*MulticastToRoomReq) Descriptor() ([]byte, []int) {
	return file_internal_push_proto_rawDescGZIP(), []int{2}
}

func (x *MulticastToRoomReq) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *MulticastToRoomReq) GetOpCode() uint32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *MulticastToRoomReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MulticastToRoomRes 组播响应
type MulticastToRoomRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"` // 错误码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MulticastToRoomRes) Reset() {
	*x = MulticastToRoomRes{}
	mi := &file_internal_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastToRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastToRoomRes) ProtoMessage() {}

func (x *MulticastToRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastToRoomRes.ProtoReflect.Descriptor instead.
func (*MulticastToRoomRes) Descriptor() ([]byte, []int) {
	return file_internal_push_proto_rawDescGZIP(), []int{3}
}

func (x *MulticastToRoomRes) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

var File_internal_push_proto protoreflect.FileDescriptor

const file_internal_push_proto_rawDesc = "" +
	"\n" +
	"\x13internal_push.proto\x12\tframework\x1a\x0eerr_code.proto\"T\n" +
	"\rPushToUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aop_code\x18\x02 \x01(\rR\x06opCode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"7\n" +
	"\rPushToUserRes\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code\"m\n" +
	"\x12MulticastToRoomReq\x12$\n" +
	"\x0eanchor_open_id\x18\x01 \x01(\tR\fanchorOpenId\x12\x17\n" +
	"\aop_code\x18\x02 \x01(\rR\x06opCode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"<\n" +
	"\x12MulticastToRoomRes\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code2\xa8\x01\n" +
	"\x13InternalPushService\x12@\n" +
	"\n" +
	"PushToUser\x12\x18.framework.PushToUserReq\x1a\x18.framework.PushToUserRes\x12O\n" +
	"\x0fMulticastToRoom\x12\x1d.framework.MulticastToRoomReq\x1a\x1d.framework.MulticastToRoomResB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_internal_push_proto_rawDescOnce sync.Once
	file_internal_push_proto_rawDescData []byte
)

func file_internal_push_proto_rawDescGZIP() []byte {
	file_internal_push_proto_rawDescOnce.Do(func() {
		file_internal_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_push_proto_rawDesc), len(file_internal_push_proto_rawDesc)))
	})
	return file_internal_push_proto_rawDescData
}

var file_internal_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_push_proto_goTypes = []any{
	(*PushToUserReq)(nil),      // 0: framework.PushToUserReq
	(*PushToUserRes)(nil),      // 1: framework.PushToUserRes
	(*MulticastToRoomReq)(nil), // 2: framework.MulticastToRoomReq
	(*MulticastToRoomRes)(nil), // 3: framework.MulticastToRoomRes
	(ErrCode)(0),               // 4: framework.ErrCode
}
var file_internal_push_proto_depIdxs = []int32{
	4, // 0: framework.PushToUserRes.code:type_name -> framework.ErrCode
	4, // 1: framework.MulticastToRoomRes.code:type_name -> framework.ErrCode
	0, // 2: framework.InternalPushService.PushToUser:input_type -> framework.PushToUserReq
	2, // 3: framework.InternalPushService.MulticastToRoom:input_type -> framework.MulticastToRoomReq
	1, // 4: framework.InternalPushService.PushToUser:output_type -> framework.PushToUserRes
	3, // 5: framework.InternalPushService.MulticastToRoom:output_type -> framework.MulticastToRoomRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_push_proto_init() }
func file_internal_push_proto_init() {
	if File_internal_push_proto != nil {
		return
	}
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_push_proto_rawDesc), len(file_internal_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_push_proto_goTypes,
		DependencyIndexes: file_internal_push_proto_depIdxs,
		MessageInfos:      file_internal_push_proto_msgTypes,
	}.Build()
	File_internal_push_proto = out.File
	file_internal_push_proto_goTypes = nil
	file_internal_push_proto_depIdxs = nil
}
