// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: op_code.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 操作码定义
//
// 号段分配规则：
//   - 每个模块保留 1000 个号段
//   - 0-999: 系统保留
//   - 1000-1999: Login 模块
//   - 2000-2999: Gateway 模块
//   - ...
type OpCode int32

const (
	// ============================================================
	// 系统保留 (0-999)
	// ============================================================
	OpCode_OP_NONE OpCode = 0
	// 内部转发消息 (Gateway <-> Game)
	OpCode_OP_INTERNAL_FORWARD OpCode = 2000
	// 内部广播消息 (Game -> Gateway)
	OpCode_OP_INTERNAL_BROADCAST OpCode = 2001
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0:    "OP_NONE",
		2000: "OP_INTERNAL_FORWARD",
		2001: "OP_INTERNAL_BROADCAST",
	}
	OpCode_value = map[string]int32{
		"OP_NONE":               0,
		"OP_INTERNAL_FORWARD":   2000,
		"OP_INTERNAL_BROADCAST": 2001,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_op_code_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_op_code_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_op_code_proto_rawDescGZIP(), []int{0}
}

var File_op_code_proto protoreflect.FileDescriptor

const file_op_code_proto_rawDesc = "" +
	"\n" +
	"\rop_code.proto\x12\tframework*K\n" +
	"\x06OpCode\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\x18\n" +
	"\x13OP_INTERNAL_FORWARD\x10\xd0\x0f\x12\x1a\n" +
	"\x15OP_INTERNAL_BROADCAST\x10\xd1\x0fB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_op_code_proto_rawDescOnce sync.Once
	file_op_code_proto_rawDescData []byte
)

func file_op_code_proto_rawDescGZIP() []byte {
	file_op_code_proto_rawDescOnce.Do(func() {
		file_op_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)))
	})
	return file_op_code_proto_rawDescData
}

var file_op_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_op_code_proto_goTypes = []any{
	(OpCode)(0), // 0: framework.OpCode
}
var file_op_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_code_proto_init() }
func file_op_code_proto_init() {
	if File_op_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_code_proto_goTypes,
		DependencyIndexes: file_op_code_proto_depIdxs,
		EnumInfos:         file_op_code_proto_enumTypes,
	}.Build()
	File_op_code_proto = out.File
	file_op_code_proto_goTypes = nil
	file_op_code_proto_depIdxs = nil
}
