// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: verify_token.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerifyTokenReq Gateway 向 Login 验证 Token 请求
//
// 使用场景：
//  1. 客户端连接 Gateway 后，携带 Token 进行认证
//  2. Gateway 收到 Token 后，向 Login 服务验证有效性
type VerifyTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端提供的 Token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 客户端 IP（用于安全校验，可选）
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// 设备 ID（用于多端登录控制，可选）
	DeviceId      string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	mi := &file_verify_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_verify_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_verify_token_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyTokenReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerifyTokenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// VerifyTokenRsp Login 返回的验证结果
type VerifyTokenRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	Code ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"`
	// 错误信息（当 code != ERR_SUCCESS 时）
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 用户 ID（验证成功时返回）
	UserId uint64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 用户唯一标识（验证成功时返回）
	UserUuid string `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// Token 剩余有效时间（秒）
	Ttl int64 `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// 用户附加信息
	UserInfo      *UserInfo `protobuf:"bytes,6,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRsp) Reset() {
	*x = VerifyTokenRsp{}
	mi := &file_verify_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRsp) ProtoMessage() {}

func (x *VerifyTokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_verify_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRsp.ProtoReflect.Descriptor instead.
func (*VerifyTokenRsp) Descriptor() ([]byte, []int) {
	return file_verify_token_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenRsp) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

func (x *VerifyTokenRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyTokenRsp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenRsp) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *VerifyTokenRsp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *VerifyTokenRsp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// UserInfo 用户基础信息
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 昵称
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像 URL
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 账号等级/VIP 等级
	Level int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	// 扩展字段（JSON 格式，业务自定义）
	Extra         string `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_verify_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_verify_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_verify_token_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// GetUserProfileReq 获取用户信息请求
type GetUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReq) Reset() {
	*x = GetUserProfileReq{}
	mi := &file_verify_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReq) ProtoMessage() {}

func (x *GetUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_verify_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileReq) Descriptor() ([]byte, []int) {
	return file_verify_token_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserProfileRsp 获取用户信息响应
type GetUserProfileRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=code,proto3,enum=framework.ErrCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRsp) Reset() {
	*x = GetUserProfileRsp{}
	mi := &file_verify_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRsp) ProtoMessage() {}

func (x *GetUserProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_verify_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRsp.ProtoReflect.Descriptor instead.
func (*GetUserProfileRsp) Descriptor() ([]byte, []int) {
	return file_verify_token_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileRsp) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

func (x *GetUserProfileRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserProfileRsp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_verify_token_proto protoreflect.FileDescriptor

const file_verify_token_proto_rawDesc = "" +
	"\n" +
	"\x12verify_token.proto\x12\tframework\x1a\x0eerr_code.proto\"`\n" +
	"\x0eVerifyTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\xcc\x01\n" +
	"\x0eVerifyTokenRsp\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_uuid\x18\x04 \x01(\tR\buserUuid\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x03R\x03ttl\x120\n" +
	"\tuser_info\x18\x06 \x01(\v2\x13.framework.UserInfoR\buserInfo\"j\n" +
	"\bUserInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05extra\x18\n" +
	" \x01(\tR\x05extra\"0\n" +
	"\x11GetUserProfileReq\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"\x87\x01\n" +
	"\x11GetUserProfileRsp\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.framework.ErrCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\tuser_info\x18\x03 \x01(\v2\x13.framework.UserInfoR\buserInfo2\xa0\x01\n" +
	"\vAuthService\x12C\n" +
	"\vVerifyToken\x12\x19.framework.VerifyTokenReq\x1a\x19.framework.VerifyTokenRsp\x12L\n" +
	"\x0eGetUserProfile\x12\x1c.framework.GetUserProfileReq\x1a\x1c.framework.GetUserProfileRspB;Z9github.com/lk2023060901/xiaojia-proto-framework;frameworkb\x06proto3"

var (
	file_verify_token_proto_rawDescOnce sync.Once
	file_verify_token_proto_rawDescData []byte
)

func file_verify_token_proto_rawDescGZIP() []byte {
	file_verify_token_proto_rawDescOnce.Do(func() {
		file_verify_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verify_token_proto_rawDesc), len(file_verify_token_proto_rawDesc)))
	})
	return file_verify_token_proto_rawDescData
}

var file_verify_token_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_verify_token_proto_goTypes = []any{
	(*VerifyTokenReq)(nil),    // 0: framework.VerifyTokenReq
	(*VerifyTokenRsp)(nil),    // 1: framework.VerifyTokenRsp
	(*UserInfo)(nil),          // 2: framework.UserInfo
	(*GetUserProfileReq)(nil), // 3: framework.GetUserProfileReq
	(*GetUserProfileRsp)(nil), // 4: framework.GetUserProfileRsp
	(ErrCode)(0),              // 5: framework.ErrCode
}
var file_verify_token_proto_depIdxs = []int32{
	5, // 0: framework.VerifyTokenRsp.code:type_name -> framework.ErrCode
	2, // 1: framework.VerifyTokenRsp.user_info:type_name -> framework.UserInfo
	5, // 2: framework.GetUserProfileRsp.code:type_name -> framework.ErrCode
	2, // 3: framework.GetUserProfileRsp.user_info:type_name -> framework.UserInfo
	0, // 4: framework.AuthService.VerifyToken:input_type -> framework.VerifyTokenReq
	3, // 5: framework.AuthService.GetUserProfile:input_type -> framework.GetUserProfileReq
	1, // 6: framework.AuthService.VerifyToken:output_type -> framework.VerifyTokenRsp
	4, // 7: framework.AuthService.GetUserProfile:output_type -> framework.GetUserProfileRsp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_verify_token_proto_init() }
func file_verify_token_proto_init() {
	if File_verify_token_proto != nil {
		return
	}
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verify_token_proto_rawDesc), len(file_verify_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verify_token_proto_goTypes,
		DependencyIndexes: file_verify_token_proto_depIdxs,
		MessageInfos:      file_verify_token_proto_msgTypes,
	}.Build()
	File_verify_token_proto = out.File
	file_verify_token_proto_goTypes = nil
	file_verify_token_proto_depIdxs = nil
}
